services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
      - ./app/static/img:/app/app/static/img
    restart: unless-stopped
